LibraryManagementProject2/Models/Books.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LibraryManagementProject2.Models
{
    public class Books
    {
        [Key]
        public int BookId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string SerialNumber { get; set; }

        public string Author { get; set; }

        public string Publisher { get; set; }
        [Required]
        public int qty { get; set; }
        [Required]
        public bool IsAvailable { get; set; }

        public ICollection<BorrowHistory> BorrowHistories { get; set; } 
        // 1 Book can have many BaorrowHistory
    }
}

LibraryManagementProject2/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryManagementProject2.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;



namespace LibraryManagementProject2.Controllers
{
    [Authorize]
   
    //[Authorize(Roles = "Administrator,Users")]
    public class BooksController : Controller
    {
        ApplicationDbContext db1 = new ApplicationDbContext();
        private BooksDb2 db = new BooksDb2();

        // GET: Books
        public ActionResult Index2(string bkname, string authname, string sortOrder, int? id)
        {
            //Session["userid"] = db.Users.Where(n=>n.UserId);
            ViewBag.Auth = isAdminUser();
            //Session["Userid"]= Convert.ToInt32(from p in db.Users
            //                    where p.Name == User.Identity.Name
            //                    select p.UserId);
           // var bh = db.Users.Where(x => x.Name == User.Identity.Name).Select(x=> x.UserId).ToString();
            //int bh2 = int.Parse(bh);
            //Session["Userid"] = bh2;
            //System.Diagnostics.Debug.WriteLine(Session["Userid"]);
            BooksDb2 Db2 = new BooksDb2();
            //(from p in Db2.Mybooks
            // where p.BookId == id
            // select p).ToList().ForEach(x => x.qty = x.qty + 1);

            //var userId = User.Identity.GetUserId();
            //Session["Userid"] = userId;
            //System.Diagnostics.Debug.WriteLine(Session["Userid"]);
            //BorrowHistory borrowHistory = db.BorrowHistories.Find(id);
            //db.BorrowHistories.Remove(borrowHistory);
            //db.SaveChanges();
            //return RedirectToAction("Index");
            Db2.SaveChanges();

            if (!ViewBag.Auth)//For user
            {
                var books = from b in db.Mybooks
                            where b.qty > 0
                            select b;


                if (!string.IsNullOrEmpty(bkname))
                {
                    books = books.Where(x => x.Title.Contains(bkname));

                }

                if (!string.IsNullOrEmpty(authname))
                {
                    books = books.Where(x => x.Author.Contains(authname));

                }

                ViewBag.TitleSortParam = sortOrder == "Title" ? "Title_desc" : "Title";
                ViewBag.AuthorParam = sortOrder == "Author" ? "Author_desc" : "Author";
                switch (sortOrder)
                {
                    case "Title_desc":
                        books = books.OrderByDescending(x => x.Title);
                        break;

                    case "Title":
                        books = books.OrderBy(x => x.Title);
                        break;

                    case "Author":
                        books = books.OrderBy(x => x.Author);
                        break;
                    case "Author_desc":
                        books = books.OrderByDescending(x => x.Author);
                        break;

                }

                return View(books);
            }
            else//For admin
            {
                var books = from b in db.Mybooks
                            select b;


                if (!string.IsNullOrEmpty(bkname))
                {
                    books = books.Where(x => x.Title.Contains(bkname));

                }

                if (!string.IsNullOrEmpty(authname))
                {
                    books = books.Where(x => x.Author.Contains(authname));

                }

                ViewBag.TitleSortParam = sortOrder == "Title" ? "Title_desc" : "Title";
                ViewBag.AuthorParam = sortOrder == "Author" ? "Author_desc" : "Author";
                switch (sortOrder)
                {
                    case "Title_desc":
                        books = books.OrderByDescending(x => x.Title);
                        break;

                    case "Title":
                        books = books.OrderBy(x => x.Title);
                        break;

                    case "Author":
                        books = books.OrderBy(x => x.Author);
                        break;
                    case "Author_desc":
                        books = books.OrderByDescending(x => x.Author);
                        break;

                }

                return View(books);
            }
        }
      
    
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db1));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                    return (true);
                else
                    return (false);
            }
            return (false);
         }
        
        public ActionResult Index()
        {
            //var num = "1";
            //var users = db1.Roles.Where(x=>x.Id == num);
            ViewBag.Auth = isAdminUser(); 
            return View(db.Mybooks.ToList());
        }

        // GET: Books/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Mybooks.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }
        [Authorize(Roles ="Admin")]
        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "BookId,Title,SerialNumber,Author,Publisher,qty,IsAvailable")] Books books)
        {
            if (ModelState.IsValid)
            {
                db.Mybooks.Add(books);
                db.SaveChanges();
                return RedirectToAction("Index2");
            }

            return View(books);
        }
        //[Authorize(Roles = "Administrator")]
        // GET: Books/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Mybooks.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "BookId,Title,SerialNumber,Author,Publisher,qty,IsAvailable")] Books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index2");
            }
            return View(books);
        }

        // GET: Books/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Mybooks.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Books books = db.Mybooks.Find(id);
            db.Mybooks.Remove(books);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryManagementProject2/Controllers/BorrowHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryManagementProject2.Models;
using System.Diagnostics;

namespace LibraryManagementProject2.Controllers
{
    [Authorize]
    public class BorrowHistoriesController : Controller
    {
        private BooksDb2 db = new BooksDb2();

        // GET: BorrowHistories
        public ActionResult Index(int? id,int ? id1)
        {
            bool flag = true;
            ViewBag.f = flag;
            //var s = from p in db.BorrowHistories
            //        join b ib.Users on
            //        p.UserId equals b.UserId
            //        select new { D = p, B = b };
            (from p in db.Mybooks
             where p.BookId == id
             select p).ToList().ForEach(x => x.qty = x.qty + 1);
            db.SaveChanges();


            var students = db.BorrowHistories.FirstOrDefault(s => s.BorrowHistoryId == id1);
            if (students != null)
            {
                db.BorrowHistories.Remove(students);
                db.SaveChanges();
            }


            var bh = db.BorrowHistories.Where(x=>x.User.Name==User.Identity.Name);

            //var borrowHistories = db.BorrowHistories.Include(b => b.Books).Include(b => b.User);
            return View(bh.ToList());
        }

        // GET: BorrowHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BorrowHistory borrowHistory = db.BorrowHistories.Find(id);
            if (borrowHistory == null)
            {
                return HttpNotFound();
            }
            return View(borrowHistory);
        }

        // GET: BorrowHistories/Create
        public ActionResult Create(int ?id)
        {

            string name = User.Identity.Name;//asp-net user table
            BooksDb2 db2 = new BooksDb2();
            var xx = from i in db2.Users
                     where i.Name == name
                     select i.UserId;
            

            int userid = xx.ToList().FirstOrDefault();
            ViewBag.userid1 = userid;
            Debug.WriteLine("userid is " + userid);
            ViewBag.BookId = new SelectList(db.Mybooks.Where(n => n.BookId == id), "BookId", "BookId");
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserId");
            //ViewBag.BookId = new SelectList(db.Mybooks.Where(n => n.BookId == id), "BookId", "BookId");
            
            (from p in db2.Mybooks
             where p.BookId == id
             select p).ToList().ForEach(x=>x.qty = x.qty -1);
            db2.SaveChanges();
            return View();
        }

        // POST: BorrowHistories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BorrowHistoryId,BookId,UserId,BorrowDate,ReturnDate")] BorrowHistory borrowHistory)
        {
               

            if (ModelState.IsValid)
            {
                string name = User.Identity.Name;
                BooksDb2 db2 = new BooksDb2();
                var xx = from i in db2.Users
                         where i.Name == name
                         select i.UserId;


                int userid = xx.ToList().FirstOrDefault();
                BorrowHistory bh = new BorrowHistory();
                bh.UserId = userid;
                bh.BookId = borrowHistory.BookId;
                bh.BorrowDate = borrowHistory.BorrowDate;
                bh.ReturnDate = borrowHistory.ReturnDate;

                db.BorrowHistories.Add(bh);
                db.SaveChanges();
                //  db.BorrowHistories.Add(borrowHistory);
                // db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BookId = new SelectList(db.Mybooks, "BookId", "BookId", borrowHistory.BookId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserId", borrowHistory.UserId);
            return View(borrowHistory);
        }
        [Authorize(Roles ="Admin")]
        // GET: BorrowHistories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BorrowHistory borrowHistory = db.BorrowHistories.Find(id);
            if (borrowHistory == null)
            {
                return HttpNotFound();
            }
            ViewBag.BookId = new SelectList(db.Mybooks, "BookId", "Title", borrowHistory.BookId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Name", borrowHistory.UserId);
            return View(borrowHistory);
        }

        // POST: BorrowHistories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "BorrowHistoryId,BookId,UserId,BorrowDate,ReturnDate")] BorrowHistory borrowHistory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrowHistory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BookId = new SelectList(db.Mybooks, "BookId", "Title", borrowHistory.BookId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "Name", borrowHistory.UserId);
            return View(borrowHistory);
        }

        [Authorize(Roles = "Admin")]
        // GET: BorrowHistories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BorrowHistory borrowHistory = db.BorrowHistories.Find(id);
            if (borrowHistory == null)
            {
                return HttpNotFound();
            }
            return View(borrowHistory);
        }

        // POST: BorrowHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            BorrowHistory borrowHistory = db.BorrowHistories.Find(id);
            db.BorrowHistories.Remove(borrowHistory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryManagementProject2/Views/Books/Create.cshtml
@model LibraryManagementProject2.Models.Books

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Books</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Publisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Publisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryManagementProject2/Views/Books/Delete.cshtml
@model LibraryManagementProject2.Models.Books

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Books</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryManagementProject2/Views/Books/Details.cshtml
@model LibraryManagementProject2.Models.Books

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Books</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.qty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.qty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BookId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LibraryManagementProject2/Views/Books/Edit.cshtml
@model LibraryManagementProject2.Models.Books

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Books</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BookId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Publisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Publisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.qty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.qty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.qty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LibraryManagementProject2/Views/Books/Index.cshtml
@model IEnumerable<LibraryManagementProject2.Models.Books>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Publisher)
        </th>
        @if (ViewBag.Auth)
        {
        <th>

            @Html.DisplayNameFor(model => model.qty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
        }
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SerialNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Publisher)
        </td>
        @if (ViewBag.Auth)
        {
        <td>
            @Html.DisplayFor(modelItem => item.qty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAvailable)
        </td>
        }
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BookId }) |
            @Html.ActionLink("Details", "Details", new { id=item.BookId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BookId })
        </td>
    </tr>
}

</table>

LibraryManagementProject2/Views/Books/Index2.cshtml
@model IEnumerable<LibraryManagementProject2.Models.Books>

@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index2</h2>

<p>
    
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index2", "Books", FormMethod.Post))
{
    <div>
        Book Title : @Html.TextBox("bkname")
        Author : @Html.TextBox("authname")

        <input id="submit" type="submit" value="Filter" />
        <br />
    </div>


}
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Title)*@
            @Html.ActionLink("Title", "Index2", new { sortOrder = ViewBag.TitleSortParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SerialNumber)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Author)*@
            @Html.ActionLink("Author", "Index2", new { sortOrder = ViewBag.AuthorParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Publisher)
        </th>
        @if (ViewBag.Auth)
        {
            <th>
                @Html.DisplayNameFor(model => model.qty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
        }
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher)
            </td>
@if (ViewBag.Auth)
{
            <td>
                @Html.DisplayFor(modelItem => item.qty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
}
            <td>
                @if (ViewBag.Auth)
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.BookId }) 
                }
                @Html.ActionLink("Details", "Details", new { id = item.BookId }) 
                @if (ViewBag.Auth)
                {
                    @Html.ActionLink("Delete", "Delete", new { id = item.BookId })
                }
            </td>
            <td>
                @*<input type="button" value="Accept" class="btn btn-success">*@
                @if (item.qty > 0)
                {
                    @Html.ActionLink("Assign", "Create", "BorrowHistories", new { id = item.BookId,}, new { @class = "btn btn-success" })
                }
            </td>
        </tr>
    }

</table>